# input:
#   train:
#     - /home/medical/fanqiliang/data/Prostate/TrainingData_Part1
#     - /home/medical/fanqiliang/data/Prostate/TrainingData_Part2
#     - /home/medical/fanqiliang/data/Prostate/TrainingData_Part3
#   test:
#     - /home/medical/fanqiliang/data/Prostate/TestData

# processed:
#   train: /home/medical/fanqiliang/processed_data/train
#   test: /home/medical/fanqiliang/processed_data/test



input:
  train:
    - /home/lisiyi/data/Prostate/TrainingData_Part1
    - /home/lisiyi/data/Prostate/TrainingData_Part2
    - /home/lisiyi/data/Prostate/TrainingData_Part3
  test:
    - /home/lisiyi/data/Prostate/TestData

processed:
  train: /home/lisiyi/processed_data/train
  test: /home/lisiyi/processed_data/test