input:
  train:
    - /home/fanqiliang/data/Prostate/TrainingData_Part1
    - /home/fanqiliang/data/Prostate/TrainingData_Part2
    - /home/fanqiliang/data/Prostate/TrainingData_Part3
  test:
    - /home/fanqiliang/data/Prostate/TestData

processed:
  train: /home/fanrui/fanqiliang/processed_data/train
  test: /home/fanrui/fanqiliang/processed_data/test