name: snapshot

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        
      - name: test
        env: 
          comment: ${{ github.event.issue_comment.body }}
        run: |
          echo $comment
